export const Data = [
    {
     "line1": "2089 BAKER ST",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-20",
     "price": 1099,
     "type": "House",
     "bed": 1,
     "bathroom": 1,
     "size": "5*6",
     "favorite": false,
     "houseName": "Orchard House",
     "id":1,
     "image":0
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-07-20",
     "price": 2400,
     "type": "House",
     "bed": 2,
     "bathroom": 2,
     "size": "5*7",
     "favorite": false,
     "houseName": "Meadow View",
     "id":2,
     "image":1
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-20",
     "price": 978,
     "type": "House",
     "bed": 1,
     "bathroom": 1,
     "size": "5*5",
     "favorite": false,
     "houseName": "The Hollies",
     "id":3,
     "image":2
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 3025,
     "type": "House",
     "bed": 2,
     "bathroom": 3,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Willows",
     "id":4,
     "image":3
    },
    {
     "line1": "2089 BAKER ST",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 3412,
     "type": "House",
     "bed": 2,
     "bathroom": 3,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Mill House",
     "id":5,
     "image":4
    },
    {
     "line1": "PO BOX 752",
     "city": "rodeo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 704,
     "type": "House",
     "bed": 1,
     "bathroom": 1,
     "size": "5*5",
     "favorite": false,
     "houseName": "Honeysuckle",
     "id":6,
     "image":5
    },
    {
     "line1": "1212 PARKDALE",
     "city": "Manhattan",
     "state": "New York",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 2421,
     "type": "House",
     "bed": 2,
     "bathroom": 1,
     "size": "6*7",
     "favorite": false,
     "houseName": "Ivy House",
     "id":7,
     "image":0
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 4124,
     "type": "House",
     "bed": 2,
     "bathroom": 3,
     "size": "8*7",
     "favorite": false,
     "houseName": "Corner House",
     "id":8,
     "image":1
    },
    {
     "line1": "2089 BAKER ST",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 4235,
     "type": "House",
     "bed": 3,
     "bathroom": 3,
     "size": "8*8",
     "favorite": false,
     "houseName": "Thornfield",
     "id":9,
     "image":2
    },
    {
     "line1": "PO BOX 752",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 5675,
     "type": "House",
     "bed": 3,
     "bathroom": 4,
     "size": "8*10",
     "favorite": false,
     "houseName": "Mannat",
     "id":10,
     "image":3
    },
    {
     "line1": "1212 PARKDALE",
     "city": "greely",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 1233,
     "type": "House",
     "bed": 1,
     "bathroom": 1,
     "size": "5*6",
     "favorite": false,
     "houseName": "Lilac Cottage",
     "id":11,
     "image":4
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 2342,
     "type": "House",
     "bed": 1,
     "bathroom": 2,
     "size": "5*8",
     "favorite": false,
     "houseName": "Windy Ridge",
     "id":12,
     "image":5
    },
    {
     "line1": "2089 BAKER ST",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 4232,
     "type": "House",
     "bed": 3,
     "bathroom": 3,
     "size": "6*6",
     "favorite": false,
     "houseName": "Henderson",
     "id":13,
     "image":0
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 6986,
     "type": "House",
     "bed": 4,
     "bathroom": 2,
     "size": "10*11",
     "favorite": false,
     "houseName": "Birchwood House",
     "id":14,
     "image":1
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 7890,
     "type": "House",
     "bed": 2,
     "bathroom": 2,
     "size": "12*15",
     "favorite": false,
     "houseName": "Townville",
     "id":15,
     "image":2
    },
    {
     "line1": "2089 BAKER ST",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-20",
     "price": 1099,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*6",
     "favorite": false,
     "houseName": "Orchard House",
     "id":16,
     "image":11
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-07-20",
     "price": 2400,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*7",
     "favorite": false,
     "houseName": "Meadow View",
     "id":17,
     "image":12
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-20",
     "price": 978,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*5",
     "favorite": false,
     "houseName": "The Hollies",
     "id":18,
     "image":13
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 3025,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Willows",
     "id":19,
     "image":14
    },
    {
     "line1": "2089 BAKER ST",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 3412,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Mill House",
     "id":20,
     "image":11
    },
    {
     "line1": "PO BOX 752",
     "city": "rodeo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 704,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*5",
     "favorite": false,
     "houseName": "Honeysuckle",
     "id":21,
     "image":12
    },
    {
     "line1": "1212 PARKDALE",
     "city": "Manhattan",
     "state": "New York",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 2421,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "6*7",
     "favorite": false,
     "houseName": "Ivy House",
     "id":22,
     "image":13
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 4124,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "8*7",
     "favorite": false,
     "houseName": "Corner House",
     "id":23,
     "image":14
    },
    {
     "line1": "2089 BAKER ST",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 4235,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "8*8",
     "favorite": false,
     "houseName": "Thornfield",
     "id":24,
     "image":11
    },
    {
     "line1": "PO BOX 752",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 5675,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "8*10",
     "favorite": false,
     "houseName": "Mannat",
     "id":25,
     "image":12
    },
    {
     "line1": "1212 PARKDALE",
     "city": "greely",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 1233,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*6",
     "favorite": false,
     "houseName": "Lilac Cottage",
     "id":26,
     "image":13
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 2342,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "5*8",
     "favorite": false,
     "houseName": "Windy Ridge",
     "id":27,
     "image":14
    },
    {
     "line1": "2089 BAKER ST",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 4232,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "6*6",
     "favorite": false,
     "houseName": "Henderson",
     "id":28,
     "image":11
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 6986,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "10*11",
     "favorite": false,
     "houseName": "Birchwood House",
     "id":29,
     "image":12
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 7890,
     "type": "Office",
     "bed": 0,
     "bathroom": 0,
     "size": "12*15",
     "favorite": false,
     "houseName": "Townville",
     "id":30,
     "image":13
    },
    {
     "line1": "2089 BAKER ST",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-20",
     "price": 1099,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*6",
     "favorite": false,
     "houseName": "Orchard House",
     "id":31,
     "image":15
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-07-20",
     "price": 2400,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*7",
     "favorite": false,
     "houseName": "Meadow View",
     "id":32,
     "image":16
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-20",
     "price": 978,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*5",
     "favorite": false,
     "houseName": "The Hollies",
     "id":33,
     "image":17
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 3025,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Willows",
     "id":34,
     "image":18
    },
    {
     "line1": "2089 BAKER ST",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 3412,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "6*8",
     "favorite": false,
     "houseName": "The Mill House",
     "id":35,
     "image":19
    },
    {
     "line1": "PO BOX 752",
     "city": "rodeo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 704,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*5",
     "favorite": false,
     "houseName": "Honeysuckle",
     "id":36,
     "image":15
    },
    {
     "line1": "1212 PARKDALE",
     "city": "Manhattan",
     "state": "New York",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 2421,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "6*7",
     "favorite": false,
     "houseName": "Ivy House",
     "id":37,
     "image":16
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 4124,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "8*7",
     "favorite": false,
     "houseName": "Corner House",
     "id":38,
     "image":17
    },
    {
     "line1": "2089 BAKER ST",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 4235,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "8*8",
     "favorite": false,
     "houseName": "Thornfield",
     "id":39,
     "image":18
    },
    {
     "line1": "PO BOX 752",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 5675,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "8*10",
     "favorite": false,
     "houseName": "Mannat",
     "id":40,
     "image":19
    },
    {
     "line1": "1212 PARKDALE",
     "city": "greely",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 1233,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*6",
     "favorite": false,
     "houseName": "Lilac Cottage",
     "id":41,
     "image":15
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 2342,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "5*8",
     "favorite": false,
     "houseName": "Windy Ridge",
     "id":42,
     "image":16
    },
    {
     "line1": "2089 BAKER ST",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 4232,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "6*6",
     "favorite": false,
     "houseName": "Henderson",
     "id":43,
     "image":17
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 6986,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "10*11",
     "favorite": false,
     "houseName": "Birchwood House",
     "id":44,
     "image":18
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 7890,
     "type": "Shop",
     "bed": 0,
     "bathroom": 0,
     "size": "12*15",
     "favorite": false,
     "houseName": "Townville",
     "id":45,
     "image":19
    },
    {
     "line1": "2089 BAKER ST",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-20",
     "price": 1099,
     "type": "Apartment",
     "size": "5*6",
     "favorite": false,
     "houseName": "Orchard House",
     "id":46,
     "image":6
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-07-20",
     "price": 2400,
     "type": "Apartment",
     "size": "5*7",
     "favorite": false,
     "houseName": "Meadow View",
     "id":47,
     "image":7
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-20",
     "price": 978,
     "type": "Apartment",
     "size": "5*5",
     "favorite": false,
     "houseName": "The Hollies",
     "id":48,
     "image":8
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "utica",
     "state": "New York",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 3025,
     "type": "Apartment",
     "size": "6*8",
     "favorite": false,
     "houseName": "The Willows",
     "id":49,
     "image":9
    },
    {
     "line1": "2089 BAKER ST",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 3412,
     "type": "Apartment",
     "size": "6*8",
     "favorite": false,
     "houseName": "The Mill House",
     "id":50,
     "image":10
    },
    {
     "line1": "PO BOX 752",
     "city": "rodeo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 704,
     "type": "Apartment",
     "size": "5*5",
     "favorite": false,
     "houseName": "Honeysuckle",
     "id":51,
     "image":6
    },
    {
     "line1": "1212 PARKDALE",
     "city": "Manhattan",
     "state": "New York",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 2421,
     "type": "Apartment",
     "size": "6*7",
     "favorite": false,
     "houseName": "Ivy House",
     "id":52,
     "image":7
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "kanata",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 4124,
     "type": "Apartment",
     "size": "8*7",
     "favorite": false,
     "houseName": "Corner House",
     "id":53,
     "image":8
    },
    {
     "line1": "2089 BAKER ST",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 4235,
     "type": "Apartment",
     "size": "8*8",
     "favorite": false,
     "houseName": "Thornfield",
     "id":54,
     "image":9
    },
    {
     "line1": "PO BOX 752",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-07-23",
     "price": 5675,
     "type": "Apartment",
     "size": "8*10",
     "favorite": false,
     "houseName": "Mannat",
     "id":55,
     "image":10
    },
    {
     "line1": "1212 PARKDALE",
     "city": "greely",
     "state": "ottawa",
     "country": "Canada",
     "Date": "2023-07-23",
     "price": 1233,
     "type": "Apartment",
     "size": "5*6",
     "favorite": false,
     "houseName": "Lilac Cottage",
     "id":56,
     "image":6
    },
    {
     "line1": "17 AIRPORT FWY",
     "city": "centla",
     "state": "tabasco",
     "country": "Mexico",
     "Date": "2023-07-23",
     "price": 2342,
     "type": "Apartment",
     "size": "5*8",
     "favorite": false,
     "houseName": "Windy Ridge",
     "id":57,
     "image":7
    },
    {
     "line1": "2089 BAKER ST",
     "city": "miami",
     "state": "Florida",
     "country": "USA",
     "Date": "2023-08-10",
     "price": 4232,
     "type": "Apartment",
     "size": "6*6",
     "favorite": false,
     "houseName": "Henderson",
     "id":58,
     "image":8
    },
    {
     "line1": "PO BOX 752",
     "city": "Airdrie",
     "state": "calgary",
     "country": "Canada",
     "Date": "2023-08-10",
     "price": 6986,
     "type": "Apartment",
     "size": "10*11",
     "favorite": false,
     "houseName": "Birchwood House",
     "id":59,
     "image":9
    },
    {
     "line1": "1212 PARKDALE",
     "city": "lerdo",
     "state": "Durango",
     "country": "Mexico",
     "Date": "2023-08-10",
     "price": 7890,
     "type": "Apartment",
     "size": "12*15",
     "favorite": false,
     "houseName": "Townville",
     "id":60,
     "image":10
    }
   ];


   export const images = [
        require("./CardList/images/House1.jpeg"),
        require("./CardList/images/House2.jpeg"),
        require("./CardList/images/House3.jpeg"),
        require("./CardList/images/House4.jpeg"),
        require("./CardList/images/House5.jpeg"),
        require("./CardList/images/House6.jpeg"),
        require("./CardList/images/Apartment1.jpeg"),
        require("./CardList/images/Apartment2.jpeg"),
        require("./CardList/images/Apartment3.jpeg"),
        require("./CardList/images/Apartment4.jpeg"),
        require("./CardList/images/Apartment5.jpeg"),
        require("./CardList/images/Office1.webp"),
        require("./CardList/images/Office2.jpeg"),
        require("./CardList/images/Office3.jpeg"),
        require("./CardList/images/Office4.jpeg"),
        require("./CardList/images/Shop1.jpeg"),
        require("./CardList/images/Shop2.jpeg"),
        require("./CardList/images/Shop3.jpeg"),
        require("./CardList/images/Shop4.jpeg"),
        require("./CardList/images/Shop5.jpeg"),
   ]